### ISSUE TITLE
Implement consent page for Hydra implementation

### ISSUE THREAD

**Issue by lus** [ory/kratos-selfservice-ui-node#224]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I am currently using the latest (alpha) version of this project.
I am aware that there is a reason that it is in an **alpha** state, so this issue should not be a complaint, but rather a question
Will there be a solution implemented to be able to complete Hydra's consent flow directly with this UI?
I really like its design and want to use it while focusing on other parts of my infrastructure before implementing my own.
Thank you very much for the hard work you put into your really nice products, I am looking forward to integrating them more within my application!

### Describe your ideal solution

It would be very nice if this feature would be implemented in this UI.

### Workarounds or alternatives

A workaround that would come to my mind is using the example Hydra consumer application just for consents.

### Version

v0.11.0-alpha.0.pre.0

**Comment by aeneasr** [comment]
We will most likely add this integration here as well, but it's currently not on the priority list because our backlog is so immense and it requires testing etc...

But if you're interested in tackling this we definitely welcome any contributions!

**Comment by lus** [comment]
Alright, I understand. Unfortunately I absolutely hate developing JS/TS so I would be the wrong person for this job, but I created a simple service that implements consents + Kratos trait propagation [here](https://github.com/lus/hydra-consent) if anyone has the same requirements as I do.
Apart from that, thank you very much for the work you put into all of your projects, it's fun to set them up and use them!

**Comment by DrBu7cher** [comment]
I have a solution ready to be used over at [my fork](https://github.com/DrBu7cher/ory-selfservice-ui-node/tree/add_hydra_consent_page).

**Comment by DrBu7cher** [comment]
It also bumps versions up.

**Comment by DavidSpek** [comment]
@mattbarnicle If you would like to test that branch I pushed an image to `davidspek/kratos-selfservice-ui-node:hydra-consent-1` that you can try. I'm currently running into an issue with it though so it very well might be broken. If I manage to solve the problem I'll update with a new image you can test.

**Comment by DavidSpek** [comment]
I've solved the issue with the consent page rendering and can confirm it is working now. You can test with image `davidspek/kratos-selfservice-ui-node:hydra-consent-2`. Since the original PR is closed and a small fix needed to be added I created a new PR to get this integrated. See https://github.com/ory/kratos-selfservice-ui-node/pull/248.

**Comment by DrBu7cher** [comment]
@mattbarnicle You build by executing `docker build -t whatever .` :)

@davidspek I don’t know how the consent view got lost, but I’m glad you found it :D

**Comment by mattbarnicle** [comment]
@DavidSpek thanks for the fix and the comment. i checked out your PR and got it to build. however I still can't get it to work in my environment. but I'm not running it the way you are. I'm trying to get it working inside a local Dockerized internal network, as that is they way we run things in our projects. i don't know if you can't help out with that but i'll explain below.

@DrBu7cher sorry, i didn't properly explain myself. as i said above to David, I'm not just trying to build the project in Docker, but to build it within a Dockerized setup where this, the Hydra, and Kratos containers are all running within the same network, launched via a `docker-compose` file. i explained what i did here: https://github.com/ory/kratos/discussions/2976#discussioncomment-4917657

so i copied that same dir into the `contrib/hydra` dir in the #248 PR checkout and ran `docker-compose up --build`. the build works and i can load the welcome page in the browser, but when i click on either of the auth links (sign in or sign up), i get a 404 error. the sign up link opens this URL: http://127.0.0.1:3000/.ory/kratos/public/self-service/registration/browser?

i don't know if either of you can help with this but this is the issue I'm facing and i don't know what to do. any advice or information you could give would be fantastic. but if not that's ok. i'm currently working with Vincent from Ory on this in another branch too.

**Comment by lus** [comment]
@mattbarnicle you need to set the `KRATOS_PUBLIC_URL` to the URL users from outside can reach the public API of you Kratos instance

**Comment by DavidSpek** [comment]
You probably also need to set the following in the kratos config yaml:

```yaml
serve:
  public:
    base_url: http://some-host/.ory/kratos/public/
```

Also, don't forget to set the `HYDRA_ADMIN_URL` environment variable on the `kratos-selfservice-ui-node` container. I'm running this within Kubernetes which in this situation is exactly the same as what you are doing with docker-compose, so it definitely is possible. There are some other issues I found in the quickstart, so if you need any more help you can let me know. I can also share a helm chart I'm using for some initial testing of a new project that setups up Kratos, Hydra, Oathkeeper and this UI.

**Comment by mattbarnicle** [comment]
thanks for the feedback @lus and @DavidSpek. i already have those things set in my docker yml files. i just don't understand why they don't work with the values I've set them to.

**Comment by aeneasr** [comment]
This is done now!
